#!/usr/bin/env bash
# Change your home IP to a different one: localhost and facebook.com
echo "Updating /etc/hosts file"
{
    echo "127.0.0.2 localhost"
    echo "8.8.8.8 facebook.com"
} | sudo tee -a /etc/hosts
